### ISSUE TITLE
Building on Linux fails

### ISSUE THREAD

**Issue by rahulpowar** [davecheney/xattr#4]
Looks like this does not build for a linux target as of Go 1.5.1

```
/src/src/vendor/github.com/davecheney/xattr/xattr_linux.go:18: undefined: getxattr
/src/src/vendor/github.com/davecheney/xattr/xattr_linux.go:24: undefined: getxattr
/src/src/vendor/github.com/davecheney/xattr/xattr_linux.go:35: undefined: listxattr
/src/src/vendor/github.com/davecheney/xattr/xattr_linux.go:41: undefined: listxattr
/src/src/vendor/github.com/davecheney/xattr/xattr_linux.go:51: undefined: setxattr
/src/src/vendor/github.com/davecheney/xattr/xattr_linux.go:60: undefined: removexattr
```

There does not seem to be an equivalent of https://github.com/davecheney/xattr/blob/master/syscall_darwin.go for linux?

**Comment by davecheney** [comment]
Thanks for your error report. I cannot reproduce the issue, the package builds cleanly on linux. Can you please post the output of

      go build -x github.com/davecheney/xattr

`https://github.com/davecheney/xattr/blob/master/xattr_linux.go` exists

**Comment by rahulpowar** [comment]
```
$:/tmp# go build -x github.com/davecheney/xattr
WORK=/tmp/go-build251114186
mkdir -p $WORK/github.com/davecheney/xattr/_obj/
mkdir -p $WORK/github.com/davecheney/
cd /opt/gopath/src/github.com/davecheney/xattr
/opt/go/pkg/tool/linux_amd64/6g -o $WORK/github.com/davecheney/xattr.a -trimpath $WORK -p github.com/davecheney/xattr -complete -D _/opt/gopath/src/github.com/davecheney/xattr -I $WORK -pack ./xattr.go ./xattr_linux.go
# github.com/davecheney/xattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:18: undefined: getxattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:24: undefined: getxattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:35: undefined: listxattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:41: undefined: listxattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:51: undefined: setxattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:60: undefined: removexattr
```

Looking on GitHub, while https://github.com/davecheney/xattr/blob/master/xattr_linux.go exists, it calls `getxattr ` et.al. which for OS-X is defined in https://github.com/davecheney/xattr/blob/master/syscall_darwin.go as I linked above but does not include a `syscall_linux.go` (I assume?) in my checkout.

**Comment by davecheney** [comment]
I'm not sure what is going on. Which platform are you compiling on ?

**Comment by davecheney** [comment]
Hang in, your build is calling 6g. 6h was removed in go 1.5. Are you sure you installed go 1.5 correctly? Are you sure you do not have GOROOT set?

**Comment by rahulpowar** [comment]
Fair point, there may be an issue with the image I am using - it is a current ubuntu docker image with a Go 1.5.1 install that I need to look at. 

However, I can reproduce using a fairly stock install. The version of Go from the package is pretty old in the script below but it produces the same error.

```
docker run -ti ubuntu
$ apt-get update && apt-get install -y golang git
$ cd /tmp
$ mkdir test
$ cd test
$ export GOPATH=$PWD
$ go get github.com/davecheney/xattr
# github.com/davecheney/xattr
src/github.com/davecheney/xattr/xattr_linux.go:18: undefined: getxattr
src/github.com/davecheney/xattr/xattr_linux.go:24: undefined: getxattr
src/github.com/davecheney/xattr/xattr_linux.go:35: undefined: listxattr
src/github.com/davecheney/xattr/xattr_linux.go:41: undefined: listxattr
src/github.com/davecheney/xattr/xattr_linux.go:51: undefined: setxattr
src/github.com/davecheney/xattr/xattr_linux.go:60: undefined: removexattr
```

**Comment by davecheney** [comment]
If you are using a u until container, it may be that go is installed via apt which will be ahead of any custom install in $PATH. 

You did not mention which version of Ubuntu you were using my but unless it is the latest, and not upset released, you will not receive go 1.5.1

**Comment by rahulpowar** [comment]
The original issue was with a custom image based on 15.04. Not likely a path issue as in this image, Go was not installed via apt but irrespective:

The script I linked above using the stock ubuntu  should work, correct? You can try it if you have a docker host. Ends up using 14.04

**Comment by rahulpowar** [comment]
Scratch my previous output log. The host I was on had an old cache of the OS image running a Go 1.4.x, hence that output.

```
$:/tmp# go get -x github.com/davecheney/xattr
cd .
git clone https://github.com/davecheney/xattr /opt/gopath/src/github.com/davecheney/xattr
cd /opt/gopath/src/github.com/davecheney/xattr
git show-ref
cd /opt/gopath/src/github.com/davecheney/xattr
git checkout master
WORK=/tmp/go-build797213813
mkdir -p $WORK/github.com/davecheney/xattr/_obj/
mkdir -p $WORK/github.com/davecheney/
cd /opt/gopath/src/github.com/davecheney/xattr
/opt/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/davecheney/xattr.a -trimpath $WORK -p github.com/davecheney/xattr -complete -buildid e471c92019b3634cd83e09fc31a8dc831d21f41f -D _/opt/gopath/src/github.com/davecheney/xattr -I $WORK -pack ./xattr.go ./xattr_linux.go
# github.com/davecheney/xattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:18: undefined: getxattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:24: undefined: getxattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:35: undefined: listxattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:41: undefined: listxattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:51: undefined: setxattr
/opt/gopath/src/github.com/davecheney/xattr/xattr_linux.go:60: undefined: removexattr
```

**Comment by davecheney** [comment]
Hello,

I'm sorry this was my mistake, there were local commits from two years that I had not pushed.

Given that I last worked on this package back in 2013, i'd regard it with deep suspicion. 

If you need extended attr support, I recommend adding to to the golang.org/x/sys repository.
